# https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines
language: node_js
sudo: false

node_js:
  - "8"

os:
  - linux

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi

install:
  - npm ci

script:
  - npm test --silent

branches:
  only:
    - master

notifications:
  email: false
