# https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines
language: node_js
sudo: false

node_js:
  - "8"

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then
      brew update;
      brew install shellcheck;
    fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm run tslint
  # - npm test --silent

notifications:
  email: false
