steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.1'
  displayName: 'Use Node.js 10.15.1'

- task: Npm@1
  displayName: 'npm install'

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: custom
    customCommand: run build
