- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: common/build.yml
  - template: common/lint.yml
  - template: common/test.yml

- job: macOS
  pool:
    vmImage: macOS 10.13
  steps:
  - template: common/build.yml
  - template: common/lint.yml
  - template: common/test.yml
